INSERT INTO FLOWERS(ID, NAME, PRICE, AMOUNT) VALUES  (1,'Roses',500,100);
INSERT INTO FLOWERS(ID, NAME, PRICE,AMOUNT) VALUES  (2,'Peons',100,80);
INSERT INTO FLOWERS(ID, NAME, PRICE,AMOUNT) VALUES  (3,'Tulips',250,120);
INSERT INTO FLOWERS(ID, NAME, PRICE,AMOUNT) VALUES  (4,'Lilies',300,50);
INSERT INTO FLOWERS(ID, NAME, PRICE,AMOUNT) VALUES  (5,'Orchid',650,45);